development:
  bucket: alphadelta-dev
  access_key_id: <%= ENV["S3_KEY"] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>
test:
  bucket: alphadelta-test
  access_key_id: <%= ENV["S3_KEY"] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>
production:
  bucket: alphadelta-pro
  access_key_id: <%= ENV["S3_KEY"] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>